name: Code for DC
url: http://calm-jackal.cloudvent.net
repository: http://github.com/carlvlewis/codefordc
markdown: kramdown
highlighter: rouge
paginate: 10
paginate_path: "/blog/:num"
gems:
- jekyll-sitemap
collections:
    resources:
        output: true
exclude:
- vendor
- README.md
- LICENSE
- Gemfile
- Gemfile.lock
